### ISSUE TITLE
i got the follwing error running whiel node app.js .. can any one help me i am new to node js and angulr js ?

### ISSUE THREAD

**Issue by AbdulMalik42** [btford/angular-express-blog#19]
body-parser deprecated bodyParser: use individual json/urlencoded middlewares ap
p.js:28:9
body-parser deprecated undefined extended: provide extended option node_modules\
body-parser\index.js:105:29
C:\Users\AbdulMalik\Desktop\btford-angular-express-seed-50ba978\btford-angular-e
xpress-seed-50ba978\node_modules\express\lib\express.js:89
      throw new Error('Most middleware (like ' + name + ') is no longer bundled
with Express and must be installed separately. Please see https://github.com/sen
chalabs/connect#middleware.');
      ^

Error: Most middleware (like errorHandler) is no longer bundled with Express and
 must be installed separately. Please see https://github.com/senchalabs/connect#
middleware.
    at Function.Object.defineProperty.get (C:\Users\AbdulMalik\Desktop\btford-an
gular-express-seed-50ba978\btford-angular-express-seed-50ba978\node_modules\expr
ess\lib\express.js:89:13)
    at Object.<anonymous> (C:\Users\AbdulMalik\Desktop\btford-angular-express-se
ed-50ba978\btford-angular-express-seed-50ba978\app.js:36:18)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

**Comment by zadiki** [comment]
i think you are missing any of these or they are not correctly ststed 
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({extended: true}));
